### PR TITLE
Front back end

### PR DESCRIPTION
**Pull request by itsClay**
Finished up some styles, got messaging to render, have some dummy info in there for now and planning on working with Tyler tomorrow to get the data flow

### CODE REVIEW

**Comment by itsClay** [comment]
I went ahead and tried to resolve conflicts the GUI way to see if its easier. 2 were just the .expo and random generator things that haven't been gitignored yet

**Review by hkumar1993 — APPROVED** [review]
Messages view approved

**Review by itsClay — COMMENTED** [review]
someone review me

**Review by tylerwood-io — APPROVED** [review]
Clay said he reviewed it

**Comment by thai321** [comment]
great!

**Pull request merged**
